import { MdHome } from 'react-icons/md';

export default {
  title: 'Home Page',
  name: 'homePage',
  type: 'document',
  icon: MdHome,
  __experimental_actions: [/* 'create', 'delete', */ 'update', 'publish'],
  description: 'The home page',
  fieldsets: [
    { name: 'header', title: 'Header section' },
    { name: 'quote', title: 'Quote section' },
    { name: 'greeting', title: 'Greeting section' },
  ],
  fields: [
    {
      title: 'Title',
      name: 'headerTitle',
      type: 'string',
      description: 'The title of the page',
      validation: (R) => R.required(),
      fieldset: 'header',
    },
    {
      title: 'Sub title',
      name: 'headerSubTitle',
      type: 'text',
      rows: 3,
      description: 'The sub title of the page',
      validation: (R) => R.required(),
      fieldset: 'header',
    },
    {
      title: 'Button link',
      name: 'headerAction',
      type: 'link',
      validation: (R) => R.required(),
      fieldset: 'header',
    },
    {
      title: 'Links',
      name: 'links',
      type: 'array',
      of: [{ type: 'actionLink' }],
      validation: (R) => R.max(3).min(3),
    },
    {
      title: 'Wines',
      name: 'wines',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'wine' }, { type: 'wineCase' }] }],
      validation: (R) => R.max(4),
    },
    {
      title: 'Quote',
      name: 'quote',
      type: 'text',
      rows: 5,
      validation: (R) => R.required(),
      fieldset: 'quote',
    },
    {
      title: 'Button link',
      name: 'quoteAction',
      type: 'link',
      validation: (R) => R.required(),
      fieldset: 'quote',
    },
    {
      title: 'Title',
      name: 'greetingTitle',
      type: 'string',
      description: 'The title of the content section',
      validation: (R) => R.required(),
      fieldset: 'greeting',
    },
    {
      title: 'Content',
      name: 'greetingContent',
      type: 'array',
      description: 'The body of the content section',
      of: [{ type: 'block' }, { type: 'link' }],
      validation: (R) => R.required(),
      fieldset: 'greeting',
    },
  ],
};
